### ISSUE TITLE
SocialController not found

### ISSUE THREAD

**Issue by RamyRais** [ITLized/social#1]
Hello, the social controller configured in the route doesn't exist

**Comment by romansavrulin** [comment]
@RamyRais see https://github.com/ITLized/social/commit/377319027828e370627dd97ba2b7daa5f1a34910

**Comment by RamyRais** [comment]
(y) thanks

**Comment by MichaelBui** [comment]
http://symfony.com/doc/current/cookbook/bundles/override.html

> ### Routing
> 
> Routing is never automatically imported in Symfony. If you want to include the routes from any bundle, then they must be manually imported from somewhere in your application (e.g. app/config/routing.yml).
> The easiest way to "override" a bundle's routing is to never import it at all. Instead of importing a third-party bundle's routing, simply copy that routing file into your application, modify it, and import it instead.
